### PR TITLE
Add support for propagating argument data into Python.

### PR DESCRIPTION
**Pull request by EdSchouten**
At the root, add a key called "args". This may contain a subtree of
arguments that are passed on to the Python script under 'sys.argdata'.
Right now all types are supported, with the exception of file
descriptors. This will be added later on.

### CODE REVIEW

**Comment by EdSchouten** [comment]
Proof that this works:

```
%TAG ! tag:nuxi.nl,2015:cloudabi/
---
stderr: !fd stderr
path: !file
  path: /usr/local/x86_64-unknown-cloudabi/lib/python3.6
nousersite: true
nosite: true
args:
    a: !!int 5
    b: !!bool false
    c:
      - !!int 1
      - !!int 2
      - !!int 3
    d: "H\0ello"
command: >-
    import sys;
    print(repr(sys.argdata), file=sys.stderr);
```

Yields:

```
{'d': 'H\x00ello', 'c': [1, 2, 3], 'b': False, 'a': 5}
```

**Comment by EdSchouten** [comment]
File descriptors now work as well:

```
args:
    a: !!int 5
    b: !!bool false
    c:
      - !!int 1
      - !!int 2
      - !!int 3
    d: "H\0ello"
    e: !fd stderr
command: >-
    import sys;
    sys.argdata['e'].write(bytes(repr(sys.argdata), encoding='ASCII'));
```

This now yields:

```
{'d': 'H\x00ello', 'e': <_io.FileIO name=0 mode='rb+' closefd=False>, 'b': False, 'c': [1, 2, 3], 'a': 5}
```

**Comment by EdSchouten** [comment]
With these changes (and a couple of other unrelated fixups to Lib/*.py), I can now get a webserver running, using this YAML file: http://80386.nl/pub/webserver.yaml.txt

Now the question is: should sockets passed in through argdata be exposed as file descriptors or as actual socket objects? @moreati, what do you think?

**Comment by EdSchouten** [comment]
Just patched up the code to create `socket.socket` objects. It's awesome to see with how little code you can now get some interesting things working!

**Comment by moreati** [comment]
Sorry for my lack of response on these, the last week has been a bit hectic.

I agree with exposing `sys.argdata`, rather than having an argdata module. I'm unsure whether the best place for `sys.argdata` to read from is
- a subkey of the argdata file (e.g. `args` as you've done),
- the top level of the argdata
- the top level of the argdata, minus any keys interpreted by Python
- a seperate YAML document, inside the same stream, e.g.

```
---
command: >-
    import sys;
    sys.argdata['e'].write(bytes(repr(sys.argdata), encoding='ASCII'));
---
a: !!int 5
b: !!bool false
c:
    - !!int
    - !!int 2
    - !!int 3
d: "H\0ello"
e: !fd stderr
```

**Comment by EdSchouten** [comment]
Absolutely no problem! Separate YAML documents would be tricky, as argdata doesn't support that at all. Let's give the subkey approach a try for now. If it turns out it's a bad idea, we can always refine. :-)

**Comment by moreati** [comment]
> Now the question is: should sockets passed in through argdata be exposed as file descriptors or as actual socket objects? @moreati, what do you think?

I'm in two minds about this, ditto for `sys.path == [0, 1, ...]` vs e.g. `sys.path == [<dirent(0, mode='r') at 0xabcd>, ...]`. Full blown objects are convenient & easier to interpret in e.g. a traceback, but they're less flexible and could hurt startup times.  File descriptors (represent as int) leave more control in the hands of the end user, but they're not in any way self describing.

I'm tempted to suggest a new FileDescriptor class/type, inheriting from int, but that's probably taking things to far.

ETA: As you say, whatever we do now isn't set in stone, it's early enough to change it.

**Pull request merged**
