### PR TITLE
Use gzip compression for the Debian control file instead of xz.

### PR DESCRIPTION
**Pull request by sgielen**
dpkg 1.17.5 doesn't support control.tar.xz yet, and is the version of dpkg
still used in Ubuntu Trusty.

Currently testing this. I'll check whether this produces correct .deb files with a correct control.tar.gz and then we can merge if you agree with the patch :)

### CODE REVIEW

**Comment by sgielen** [comment]
```
➜ sjors@charmander  /tmp/2017-07-23-13-51-41 ar x x86-64-unknown-cloudabi-cloudabi_0.11-1_all.deb
➜ sjors@charmander  /tmp/2017-07-23-13-51-41 ls
control.tar.gz
data.tar.xz
debian-binary
x86-64-unknown-cloudabi-cloudabi_0.11-1_all.deb
➜ sjors@charmander  /tmp/2017-07-23-13-51-41 file control.tar.gz 
control.tar.gz: gzip compressed data, last modified: Sun Jul 23 11:51:27 2017, from Unix
➜ sjors@charmander  /tmp/2017-07-23-13-51-41 file data.tar.xz 
data.tar.xz: XZ compressed data
```

**Comment by EdSchouten** [comment]
Achtung! There's a 'last modified' date in there. We need to pass in an explicit command line flag to have libarchive omit that.

**Comment by sgielen** [comment]
I can't really find a flag to omit that... I can't find it in the `gzip` man page as well?

Also, won't current 'last modified' dates for all files be stored in the tarball as well, by the way?

**Comment by sgielen** [comment]
Ah, Maurice explained the details to me: libarchive is patched not to store any last modified dates or other metadata. I added the correct option to the bsdtar invocation to remove the timestamp, it seems to work:

```
control.tar.gz: gzip compressed data, from Unix
```

**Comment by EdSchouten** [comment]
Perfect!

Yeah, we want to make sure that packages are byte for byte reproducible. cloudabi-ports uses this to determine whether package revisions have to be bumped, due to ABI changes.

**Pull request merged**
